config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :receptionists, only: [:index]
  resources :doctors, only: [:index]
  resources :patients

  get 'dashboard', to: 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?, :require_user
  
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  
    def logged_in?
      !current_user.nil?
    end
  
    def require_user
      unless logged_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to root_path
      end
    end
  
    def require_receptionist
      unless current_user&.role == 'receptionist'
        flash[:error] = "You must be a receptionist to access this section"
        redirect_to root_path
      end
    end
  
    def require_doctor
      unless current_user&.role == 'doctor'
        flash[:error] = "You must be a doctor to access this section"
        redirect_to root_path
      end
    end
  end
  

app/controllers/dashboard_controller.rb
# app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_user

  def index
    # You can add any logic here if needed
  end
  def require_user
    unless current_user
      flash[:alert] = "You must be logged in to access this section"
      redirect_to new_session_path
    end
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :require_user
  before_action :require_doctor

  def index
    @patients = Patient.all
    @patient_registration_chart = Patient.group_by_minute(:created_at).count
  end
  private

  def require_doctor
    unless current_user.role == 'doctor'
      flash[:alert] = "Access restricted to doctors only."
      redirect_to root_path
    end
  end
end

app/controllers/patients_controller.rb
# app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :require_user
  before_action :require_receptionist, except: [:index, :show]

  def index
    @patients = Patient.all
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to patients_path, notice: 'Patient was successfully created.'
    else
      render :new
    end
  end

  def update
    if @patient.update(patient_params)
      redirect_to patients_path, notice: 'Patient was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
    redirect_to patients_path, notice: 'Patient was successfully deleted.'
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :date_of_birth)
  end
end

app/controllers/receptionists_controller.rb
class ReceptionistsController < ApplicationController
  before_action :require_user
  before_action :require_receptionist

  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to receptionists_path
    else
      render :new
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update(patient_params)
      redirect_to receptionists_path
    else
      render :edit
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
    redirect_to receptionists_path
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :date_of_birth)
  end
end

class DoctorsController < ApplicationController
  before_action :require_user
  before_action :require_doctor

  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      flash[:error] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out successfully"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/receptionists_helper.rb
module ReceptionistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/dashboard/index.html.erb
<!-- app/views/dashboard/index.html.erb -->
<h1>Welcome to the Dashboard</h1>
<p>You are logged in as <%= current_user.email %></p>

app/views/doctors/index.html.erb
<!-- app/views/doctors/index.html.erb -->
<h1>Patients</h1>

<%= area_chart @patient_registration_chart, library: { title: { text: "Patients Registered Over Time" }, yAxis: { title: { text: "Number of Patients" } } } %>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Date of Birth</th>
      <th>Registered At</th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.date_of_birth %></td>
        <td><%= patient.created_at.localtime %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/doctors/show.html.erb
<h1>Doctors#show</h1>
<p>Find me in app/views/doctors/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClinicManagement</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
</head>
<body>
  <nav>
    <ul>
      <% if logged_in? %>
        <li><%= link_to 'Dashboard', dashboard_path %></li>
        <li><%= button_to 'Logout', session_path(current_user), method: :delete %></li>
        <% if current_user.role == 'receptionist' %>
          <li><%= link_to 'Manage Patients', patients_path %></li>
        <% elsif current_user.role == 'doctor' %>
          <li><%= link_to 'View Patients', doctors_path %></li>
        <% end %>
      <% else %>
        <li><%= link_to 'Login', new_session_path %></li>
      <% end %>
    </ul>
  </nav>
  <% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
  <% elsif flash[:error] %>
    <p><%= flash[:error] %></p>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/patients/create.html.erb
<h1>Patients#create</h1>
<p>Find me in app/views/patients/create.html.erb</p>

app/views/patients/destroy.html.erb
<h1>Patients#destroy</h1>
<p>Find me in app/views/patients/destroy.html.erb</p>

app/views/patients/edit.html.erb
<!-- app/views/patients/edit.html.erb -->
<h1>Edit Patient</h1>
<%= form_with model: @patient, local: true do |form| %>
  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>
  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>
  <div>
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth %>
  </div>
  <div>
    <%= form.submit 'Update Patient' %>
  </div>
<% end %>

app/views/patients/index.html.erb
<!-- app/views/patients/index.html.erb -->
<h1>Patients</h1>
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Date of Birth</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.date_of_birth %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= button_to patient, method: :delete do %>  Delete <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<!-- app/views/patients/new.html.erb -->
<h1>New Patient</h1>
<%= form_with model: @patient, local: true do |form| %>
  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>
  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>
  <div>
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth %>
  </div>
  <div>
    <%= form.submit 'Create Patient' %>
  </div>
<% end %>

app/views/patients/show.html.erb
<!-- app/views/patients/show.html.erb -->
<h1>Patient Details</h1>
<p>
  <strong>First Name:</strong>
  <%= @patient.first_name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @patient.last_name %>
</p>
<p>
  <strong>Date of Birth:</strong>
  <%= @patient.date_of_birth %>
</p>
<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back to Patients', patients_path %>

app/views/patients/update.html.erb
<h1>Patients#update</h1>
<p>Find me in app/views/patients/update.html.erb</p>

app/views/receptionists/create.html.erb
<h1>Receptionists#create</h1>
<p>Find me in app/views/receptionists/create.html.erb</p>

app/views/receptionists/destroy.html.erb
<h1>Receptionists#destroy</h1>
<p>Find me in app/views/receptionists/destroy.html.erb</p>

app/views/receptionists/edit.html.erb
<h1>Receptionists#edit</h1>
<p>Find me in app/views/receptionists/edit.html.erb</p>

app/views/receptionists/index.html.erb
<h1>Receptionists#index</h1>
<p>Find me in app/views/receptionists/index.html.erb</p>

app/views/receptionists/new.html.erb
<h1>Receptionists#new</h1>
<p>Find me in app/views/receptionists/new.html.erb</p>

app/views/receptionists/update.html.erb
<h1>Receptionists#update</h1>
<p>Find me in app/views/receptionists/update.html.erb</p>